### PR TITLE
Fix url parse bug

### LINKED ISSUE #758: Wrong parsing URLs w/o scheme and w port
```
oatpp::String Url="example.com:8080/path";
oatpp::network::Url pUrl = oatpp::network::Url::Parser::parseUrl(Url);
```
After that, in pUrl, scheme is "example.com", host is "8080", port is -1.
But "example.com/path" parsed correctly.

### PR DESCRIPTION
**Pull request by linhaojun857**
fix #758

### CODE REVIEW

**Comment by linhaojun857** [comment]
fix url parse bug

**Comment by linhaojun857** [comment]
fix #758

**Review by lganzzzo — APPROVED** [review]
Looks good!

**Comment by lganzzzo** [comment]
Merged!

**Pull request merged**
