### PR TITLE
Added /permissive- flag on MSVC to enforce standard compliancy

### PR DESCRIPTION
**Pull request by MHaselmaier**

### CODE REVIEW

**Comment by lganzzzo** [comment]
Hey @MHaselmaier ,
Looks good.
Please change the target branch to `1.3.0`

**Comment by MHaselmaier** [comment]
Is there a better way than changing the branch here on github and remove all other changes?
Or should I delete this PR+Branch and create a new one based on v1.3.0?

**Comment by lganzzzo** [comment]
I think using GitHub UI should work.
Just ignore the warning and see what happens :)

**Comment by MHaselmaier** [comment]
The problem is now: Because this branch was branched from masters, the other changes on master would be merged to v1.3.0 also.

**Comment by lganzzzo** [comment]
Its fine with me

**Pull request merged**
