### PR TITLE
Explicitly add compiler flags

### PR DESCRIPTION
**Pull request by fhuberts**
See #784 

This should be applied after #801 and #803 to get rid of those warnings as well

### CODE REVIEW

**Review by lganzzzo — CHANGES_REQUESTED** [review]
Let us move all this to a separate cmake file and place it in `oatpp/cmake` dir.

**Comment by fhuberts** [comment]
Like this?

**Comment by fhuberts** [comment]
PS. I have 7 patches pending for fixing compiler warnings, but they depend on this one, so I'm not yet submitting those.

**Comment by lganzzzo** [comment]
> Like this?

Yes, looks good

**Comment by lganzzzo** [comment]
> PS. I have >= 7 patches pending for fixing compiler warnings, but they depend on this one, so I'm not yet submitting those.

Windows build is failing weird CMake error:

```
CMake Error at cmake/compiler-flags.cmake:60 (string):
  string no output variable specified
Call Stack (most recent call first):
  CMakeLists.txt:120 (include)
```

Code looks good to me. I don't know why it's failing.
Also, I don't have a Win machine at the moment to take a look.

**Comment by fhuberts** [comment]
Fixed the Windows build with a simple patch (bloody braindead Windows...)

**Review by lganzzzo — APPROVED** [review]

**Comment by lganzzzo** [comment]
Merged!

**Pull request merged**
