### PR TITLE
Fix comparison of signed and unsigned integers.

### PR DESCRIPTION
**Pull request by hermanzdosilovic**
To comply with `-Wsign-compare` flag.

### CODE REVIEW

**Comment by lganzzzo** [comment]
Hey @hermanzdosilovic ,

I have created a PR to your branch with minor PR-review fixes - https://github.com/hermanzdosilovic/oatpp/pull/1

Please review and merge. Then we'll merge it to master.

Regards,
Leonid

**Comment by hermanzdosilovic** [comment]
Hey @lganzzzo,

sorry for the delayed response. Thanks for the merge.

What happened with PR on my branch? Why did you decide to merge it without first merging the PR on my branch? Just curious.

**Comment by lganzzzo** [comment]
Hey @hermanzdosilovic ,

No worries,
It was merged automatically since I made fixes on top of your PR.
So when I merged my changes, your changes were merged too.

**Comment by hermanzdosilovic** [comment]
Do I need to close or merge PR you made on my fork, or it doesn't matter anymore? Sorry, I didn't know that this was possible.

**Comment by lganzzzo** [comment]
Nop, no action required :)
Thanks for heads-up anyways !

**Pull request merged**
